services:
  - type: web
    name: BookNest
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate

      # Create superuser: kapil
      DJANGO_SUPERUSER_USERNAME=kapil \
      DJANGO_SUPERUSER_PASSWORD=1234 \
      DJANGO_SUPERUSER_EMAIL=none@localhost \
      python manage.py createsuperuser --noinput || true

      # Create superuser: dev
      DJANGO_SUPERUSER_USERNAME=dev \
      DJANGO_SUPERUSER_PASSWORD=2000 \
      DJANGO_SUPERUSER_EMAIL=none@localhost \
      python manage.py createsuperuser --noinput || true

      gunicorn book_manager.wsgi:application

    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "replace-this-with-a-strong-secret-key"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
