services:
  - type: web
    name: BookNest
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate
      python manage.py createsuperuser
      gunicorn book_manager.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "your-actual-secret-key"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "kapil"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "1234"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "none@localhost"
