# Generated by Django 5.2 on 2025-06-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reference_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
